version: 2

build:
  os: ubuntu-20.04
  tools:
    python: miniconda3-4.7

python:
  version: 3.9
  install:
    - method: setuptools
      path: .

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/environment.yaml
