name: docs
channels:
  - conda-forge
  - cantera
  - defaults
dependencies:
  - compilers
  - sphinx
  - nbsphinx
  - numpy
  - scipy
  - Cython
  - matplotlib
  - numpydoc
  - setuptools
  - gitpython
  - cantera
  - pip:
    - recommonmark
    - readthedocs-sphinx-ext
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme