name: docs
channels:
  - conda-forge
  - anaconda
  - cantera
  - defaults
dependencies:
  - sphinx
  - nbsphinx
  - numpy
  - scipy
  - compilers
  - Cython
  - matplotlib
  - numpydoc
  - setuptools
  - ruamel.yaml
  - pyyaml
  - gitpython
  - pybind11
  - cantera
  - pip:
    - recommonmark
    - readthedocs-sphinx-ext
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme